### ISSUE TITLE
worth-reading.org/emails should show received emails, too.

### ISSUE THREAD

**Issue by jhm15217** [jhm15217/worthreading#105]

**Comment by mvillena3** [comment]
I'm confused was this issued renamed? I got an email saying
[worthreading] Any user can see worth-reading.org/emails (#105)
Only administrators should see

But this says differently.

**Comment by jhm15217** [comment]
Yes. I realized the first one wasn't a problem, so reused the issue for a
ne one.  But then I changed the whole approach with a later issue.

On Thu, Aug 23, 2012 at 12:45 PM, mvillena3 notifications@github.comwrote:

> I'm confused was this issued renamed? I got an email saying
> [worthreading] Any user can see worth-reading.org/emails (#105https://github.com/jhm15217/worthreading/issues/105
> )
> Only administrators should see
> 
> But this says differently.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhm15217/worthreading/issues/105#issuecomment-7975949.

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
Superceded
