### ISSUE TITLE
Improve home page

### ISSUE THREAD

**Issue by jhm15217** [jhm15217/worthreading#107]
There should be four tabs:  Sent, Received, Subscribers, Subscribed To

On the right a list of the most liked emails in the past 24 hours and (if there's room) the users with the most likes total.  This should be on the non-user home page, too.

**Comment by jhm15217** [comment]
A small remaining problem: If there are more than about 15 pages in the left panel, the page navigation tool bumps into the following table. I'm guessing this is a bug in paginate.

**Comment by mvillena3** [comment]
Interesting.... I could take a look at that this week. It could be a css styling issue.

**Comment by mvillena3** [comment]
I notice that the welcome to worth reading on the homepage when a user isn't signed in doesn't have the gray background box. Did you not like the background box there?

Here's a screenshot of the hompage. I put a red box around the issue.
![screenshot1](https://github.com/jhm15217/worthreading/blob/3171ba366d4720c1d6bb5a8de4e0f6c754e15bdd/public/images/screenshot2.png?raw=true)

Here's the box the grey box I was talking about.
![screenshot_2](https://github.com/jhm15217/worthreading/blob/3171ba366d4720c1d6bb5a8de4e0f6c754e15bdd/public/images/screenshot1.png?raw=true)

**Comment by jhm15217** [comment]
The box was good, I just lost it while thrashing.

**Comment by mvillena3** [comment]
Ok I can bring it back.
