### ISSUE TITLE
In home page, relationship, subscribers, subscribers_to the pagination interferes with the footer

### ISSUE THREAD

**Issue by jhm15217** [jhm15217/worthreading#108]
Once we start to paginate the left panel, the footer gets placed under the right panel.  Somebody (applications.html.erb?) needs to put a .break or .div somewhere.

**Comment by mvillena3** [comment]
I'll take a look

**Comment by mvillena3** [comment]
I'm not sure if I fixed the error you were talking about. But could you take a look again and if the problem still appears, could you take a screenshot of it?

**Comment by jhm15217** [comment]
You fixed it, but I broke your code merging. Then I fixed it again, I hope.
