### ISSUE TITLE
Do we want our subscriber list not to display a subscriber's email

### ISSUE THREAD

**Issue by mvillena3** [jhm15217/worthreading#116]
I noticed the subscriber list doesn't display my subscriber's email? Do we not want it to display their email address? I have two subscribers with the name Unknown on my subscriber list and I have no way of identifying them.

**Comment by jhm15217** [comment]
I replaced the names with links to the user's page and included the email address on the page.  How do you make a link come up blue?

**Comment by jhm15217** [comment]
Oh. I see that my browser controls color.
