### ISSUE TITLE
Send Emails Outbound Using Mailgun as opposed to Gmail

### ISSUE THREAD

**Issue by mvillena3** [jhm15217/worthreading#18]
We need to send outbound emails using mailgun.

**Comment by jhm15217** [comment]
A preliminary look at the Mailgun manual makes me wonder of a large amount of functionality can be outsourced. It handles distribution lists and creates analytics based on people opening messages and clicking on links. As usual, we'll need to study a lot before understanding whether we can use it or adapt it.

**Comment by jhm15217** [comment]
Upon further study, I'm in the tank for Mailgun! Rather than invent our own analytics and distribution lists, I think we should use theirs if the API will support it.

**Comment by mvillena3** [comment]
Yeah it would probably be best to use mailgun's API and take advantage of their services.

**Comment by jhm15217** [comment]
Eventually we might want to keep more data about happens to each message and manage distribution lists more delicately, so we can keep our own records, but we should probably store each user's default distribution list on mailgun.

**Comment by mvillena3** [comment]
I also noticed that mailgun checks when people opens their email; thus, we may only need to access Mailgun's records hopefully available through their API to retreive the information we need. I'll look more into that as well.

**Comment by jhm15217** [comment]
The only reason we needed the open time was for analytics, and I think we
should see what mailgun provides before worrying about doing them ourselves.

On Tue, Jul 17, 2012 at 1:12 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> I also noticed that mailgun checks when people opens their email; thus, we
> may only need to access Mailgun's records hopefully available through their
> API to retreive the information we need. I'll look more into that as well.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/issues/18#issuecomment-7042195

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
Oops. We really can't use mailgun's distribution list system since we need to insert different buttons for different receivers. Mailgun itself might do this for itself, but we don't really have control of it. We could try a hack using the %recipient% feature, but it's not worth it. Furthermore, since subscribers change according to tbd rules, we'd have to be changing the lists all the time.
