### ISSUE TITLE
Our website is named worth-reading.org

### ISSUE THREAD

**Issue by jhm15217** [jhm15217/worthreading#19]
which I bought on godaddy.com for a year. It forwards to evening-fog-9503.heroku.com

**Comment by mvillena3** [comment]
Is it suppose to be working yet?

https://devcenter.heroku.com/articles/custom-domains

**Comment by jhm15217** [comment]
Well, putting worth-reading.org in the chrome search box leads to evening-fog-9503.heroku.com, even though I didn't say "herokuapp" or tell heroku about it. I changed those things. Is there anything else I should do?

**Comment by mvillena3** [comment]
My mistake I missed the hypen.

**Comment by mvillena3** [comment]
Actually, the fact that it still says evening-fog after being redirected is an issue. You have to add a custom domain to our heroku app https://devcenter.heroku.com/articles/custom-domains. 

That way the app has worth-reading.org in the url instead of evening-fog

**Comment by mvillena3** [comment]
You also have to tell GoDaddy's DNS settings to point towards our app.
