### ISSUE TITLE
Receiving and Sending Emails

### ISSUE THREAD

**Issue by mvillena3** [jhm15217/worthreading#28]
I was noticing that when our app receives an email from mailgun, the receiver/to of the email always has the form of some_email_name@worthreading.org.mailgun.org. Thus, it doesn't actually have the actual email of the recipient.  Plus, atm our code is registering these users with these email_name@worthreading.org.mailgun.org. How should we go about dealing with that?

Should we just allow it to  be a process that whenever a user sends an email to mailgun, the message would be sent out to all their subscribers.

Or should we have some format that if they send an email to subscribers@worthreading.org.mailgun.org it sends an email to all their subscribers. But if they send an email to email_name@worthreading.org.mailgun.org, we check their subscriber list for an email with everything before the @ sign that matches email_name. Only problem is the database query and parsing may be cumbersome. Also, if there is ever the chance that there is more than one email with same email_name before the @ sign, then that could present a problem.

**Comment by jhm15217** [comment]
The sender should send it to

joe.smith@ibm.com.worth-reading.org

The we should register the receiver as joe.smith@ibm.com and send the mail
to him there. Also, the sender's address should should not mention
worth-reading or mailgun.

On Mon, Jul 23, 2012 at 5:21 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> I was noticing that when our app receives an email from mailgun, the
> receiver/to of the email always has the form of
> some_email_name@worthreading.org.mailgun.org. Thus, it doesn't actually
> have the actual email of the recipient.  Plus, atm our code is registering
> these users with these email_name@worthreading.org.mailgun.org. How
> should we go about dealing with that?
> 
> Should we just allow it to  be a process that whenever a user sends an
> email to mailgun, the message would be sent out to all their subscribers.
> 
> Or should we have some format that if they send an email to
> subscribers@worthreading.org.mailgun.org it sends an email to all their
> subscribers. But if they send an email to
> email_name@worthreading.org.mailgun.org, we check their subscriber list
> for an email with everything before the @ sign that matches email_name.
> Only problem is the database query and parsing may be cumbersome. Also, if
> there is ever the chance that there is more than one email with same
> email_name before the @ sign, then that could present a problem.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/issues/28

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
I changed the recipient address we store to be params["Delivered-to"] which is what the sender typed in their to field. That's probably OK. The receiver sees the right thing in the to field, i.e. their real address.
