### ISSUE TITLE
User's pages

### ISSUE THREAD

**Issue by jhm15217** [jhm15217/worthreading#40]
Here are all the items a user should be able to see.
1. A list of subscribers, ordered by %_liked
     Subscriber  Messages_Sent  %_opened  %_liked
   
     clicking Subscriber leads to 3.
2. A list of sent emails
     Time_sent Subject #_recipients %_opened  %_liked
   
    clicking on a #_recipients leads to 4.
3. A list of emails send to a particular subscriber 
     Time_sent Subject Time_to_open  Time_to_like
4. A list of recipients for a particular email
     Recipient  Time_to_open Time_to_like
5. A list of senders to me
     Sender  #_emails  %_opened %_liked
6. A list of received emails
     Time Sender Subject  time_to_open time_to_like
7. A list of emails received from a particular subscriber 
     Time_sent Subject Time_to_open  Time_to_like
8. Ten users with highest percentage liked
9.  How many have I liked
10.  How many times was my message liked.

**Comment by jhm15217** [comment]
I don't know if we've done all these, but it's enough for now.

**Comment by mvillena3** [comment]
Not yet. I'm still working on it.

**Comment by jhm15217** [comment]
Everything worked fine for me on localhost, but heroku said "Sorry,
something went wrong".

On Fri, Aug 17, 2012 at 4:46 PM, mvillena3 notifications@github.com wrote:

> Not yet. I'm still working on it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhm15217/worthreading/issues/40#issuecomment-7834611.

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by mvillena3** [comment]
I haven't run a rake db:migrate on heroku yet.

**Comment by mvillena3** [comment]
Oh nvm. I'll have to deal with another PG issue.

**Comment by mvillena3** [comment]
Its working now.
