### ISSUE TITLE
Site name

### ISSUE THREAD

**Issue by jhm15217** [jhm15217/worthreading#56]
The url in the browser says "evening-fog-9503.herokuapp.com" instead of worth-reading.org

**Comment by mvillena3** [comment]
Fixed. I saw you forwarded the site instead of pointing GoDaddy's DNS settings towards our site.

**Comment by mvillena3** [comment]
Also, we cannot use SSL in this case since we cannot piggyback on heroku's SSL certificate with our custom domain. We would have to obtain our own SSL certificate.
