### ISSUE TITLE
A "What's This" button

### ISSUE THREAD

**Issue by jhm15217** [jhm15217/worthreading#58]
I'm thinking many people will ignore or fear the "worth reading" button. We might include a what's this button that leads to

"The sender of your email is using a service called worth-reading.org to help him/her to understand who appreciates the messages he/she sends. If you click the Worth Reading button, your approval will be noted and might encourage them to send you similar messages in the future.

You can sign up for worth-reading.org yourself and use it to facilitate bulk mailings and track responses to them.

"Join Worth Reading"  

"Click Worth Reading for This message"

**Comment by mvillena3** [comment]
Closing since this was completed.
