### ISSUE TITLE
Add Log System to App

### ISSUE THREAD

**Issue by mvillena3** [jhm15217/worthreading#7]
Add a log model to record actions with emails

**Comment by jhm15217** [comment]
Good idea, recording all the things to do!

I think this is the first one to work on because it defines what the
more/worthreading buttons have to send and the responses the server needs
to make.  As I recall the columns are

id, Action(=:initiate, :more, :worthreading), email id, sender (user id),
recipient (user id), part (integer), request time (Time), response time
(Time)

I think I can do that one, if I can find the Rails Time code, so I'll
assign it to me. You should do ones that I'm clueless about, like the
sending process or the parsing process.

On Thu, Jul 12, 2012 at 11:42 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> Add a log model to record actions with emails
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/issues/7

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by mvillena3** [comment]
http://api.rubyonrails.org/classes/Time.html
Is the rails time code above the one you need?

**Comment by mvillena3** [comment]
also, maybe it would better to link the sender and recipient through the relationship model;
thus, use subscriber_id will denote the recipient, and the subscribed_id will denote the sender

**Comment by jhm15217** [comment]
I was going to use datetime, but then noticed that the model automatically
gets two timestamps, one for creation, one for update. So I just added a
boolean flag, responded, whose setting will record in the update column.

Also, I realize I probably don't want to be storing ids is the WRLog (the
name I chose to avoid confusion) table, but the objects themselves, Users
and Emails. When I say something like "sender: id" or "sender: User" in a
generate scaffolding command, how does Rails treat the type declarations?
Ignore them? Build in dynamic checks?

Now I'm wondering how more and worthreading requests will come in. That's
up to you with what you put in the button. The original email will come in
to the emails create, of course, o I guess I'll create the wr_log  entry
there.

On Fri, Jul 13, 2012 at 12:55 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> http://api.rubyonrails.org/classes/Time.html
> Is the rails time code above the one you need?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/issues/7#issuecomment-6968822

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
I just saw your earlier message about using the Relationship database. I'm
uncertain about the representation strategy, as I just said. Storing ids
seems like introducing needless indirection into the representation, but
I'm not sure whether the objects' identities are persist enough. In
Java-speak, I'm thinking the WRLog table can contain object references or
indices of the object in the data base. But maybe putting such references
in a table is a no-no; e.g. if store an object in table, the content of the
reference is stored, not the pointer.

On Fri, Jul 13, 2012 at 5:26 PM, james.morris@cmu.edu wrote:

> I was going to use datetime, but then noticed that the model automatically
> gets two timestamps, one for creation, one for update. So I just added a
> boolean flag, responded, whose setting will record in the update column.
> 
> Also, I realize I probably don't want to be storing ids is the WRLog (the
> name I chose to avoid confusion) table, but the objects themselves, Users
> and Emails. When I say something like "sender: id" or "sender: User" in a
> generate scaffolding command, how does Rails treat the type declarations?
> Ignore them? Build in dynamic checks?
> 
> Now I'm wondering how more and worthreading requests will come in. That's
> up to you with what you put in the button. The original email will come in
> to the emails create, of course, o I guess I'll create the wr_log  entry
> there.
> 
> On Fri, Jul 13, 2012 at 12:55 PM, mvillena3 <
> reply@reply.github.com
> 
> > wrote:
> > 
> > http://api.rubyonrails.org/classes/Time.html
> > Is the rails time code above the one you need?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jhm15217/worthreading/issues/7#issuecomment-6968822
> 
> ## 
> 
> James H. Morris
> http://www.cs.cmu.edu/~jhm

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by mvillena3** [comment]
The problem with storing the objects itself is that it is very inefficient and unreliable. If a user updates his/her info.... say they change their email address, then there is no longer connection between the user who is stored in the log and the actual user stored in the user database anymore (they both have different emails). Plus, storing objects themselves can cause our database to become very large requiring more computing power and more servers. 

I would recommend using relational database association through ids.

**Comment by mvillena3** [comment]
"When I say something like "sender: id" or "sender: User" in a generate scaffolding command, how does Rails treat the type declarations? Ignore them? Build in dynamic checks?"

I'm pretty sure Rails would bring up errors when you try to migrate (rake db:migrate) such types into the database.
http://guides.rubyonrails.org/migrations.html#supported-types

**Comment by mvillena3** [comment]
"Storing ids seems like introducing needless indirection into the representation, but I'm not sure whether the objects' identities are persist enough. In Java-speak, I'm thinking the WRLog table can contain object references or indices of the object in the data base. But maybe putting such references in a table is a no-no; e.g. if store an object in table, the content of the reference is stored, not the pointer."

If you try to store an object in a database it stores the content of the reference, not the pointer.  For web applications data mainly persist through storage in a database as integers, string, etc. depending on the DBMS you use. Thats why in RDBMS, you use DB associations and ids i.e. has_many, user_id to link objects in the databases.

**Comment by jhm15217** [comment]
Slowly, it's sinking in. Rails doesn't pass around references like Java.
Creating an object means putting its components in a table which is indexed
by an integer id. So I pass around ids and have to remember what table each
one is for. So when I say Users.find(7) the thing returned is a big data
record containing all the components, not a pointer. Is this also a fact in
Ruby?

On Fri, Jul 13, 2012 at 5:47 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> "When I say something like "sender: id" or "sender: User" in a generate
> scaffolding command, how does Rails treat the type declarations? Ignore
> them? Build in dynamic checks?"
> 
> I'm pretty sure Rails would bring up errors when you try to migrate (rake
> db:migrate) such types into the database.
> http://guides.rubyonrails.org/migrations.html#supported-types
> 
> ---s
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/issues/7#issuecomment-6976221

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by mvillena3** [comment]
On the web, objects usually persist during an HTTP request. They will not persist outside of the request unless the content of the object is either stored in a database or maybe a cookie.

i.e. I issue a GET request for a page and a controller handles that request and responds with some code implementation in ruby. Say instance variables are used to store objects such as `@user = User.first` retrieved via a database query. And that @user is used to render certain information for a view. After everything is complete (GET request issued, controller receives request and responds by rendering the view), @user no longer exists, until another GET request.

i.e. Now an example on putting an object into the database. Let's say a POST request is sent with `params = { name: "Mike", email: "mike@email.com", password: "123456" }. Those params are then used to create a User in the database. The params hash itself will not exist beyond the completion of the POST request. The only way to retrieve the contents of that particular user that was created is to use a database.

Lastly, this is not a result of Ruby, but a result of web applications in general since dealing with code running on the internet, servers, and clients is a whole lot different than dealing with code running on one computer. 

Ruby passes objects by reference. So if you wrote a Ruby program, then you can pass around references etc.

**Comment by jhm15217** [comment]
Oh, I now understand that the Ruby environment completely disappears
between events, so of course any object pointers are evanescen

On Fri, Jul 13, 2012 at 6:16 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> On the web, objects usually persist during an HTTP request. Does they will
> not persist outside of the request unless the content of the object is
> either stored in a database or maybe a cookie?
> 
> i.e. I issue a GET request for a page and a controller handles that
> request and responds with some code implementation in ruby. Say instance
> variables are used to store objects such as `@user = User.first` retrieved
> via a database query. And that @user is used to render certain information
> for a view. After everything is complete (GET request issued, controller
> receives request and responds by rendering the view), @user no longer
> exists, until another GET request.
> 
> i.e. Now an example on putting an object into the database. Let's say a
> POST request is sent with `params = { name: "Mike", email: "mike@email.com",
> password: "123456" }. Those params are then used to create a User in the
> database. The params hash itself will not exist beyond the completion of
> the POST request. The only way to retrieve the contents of that particular
> user that was created is to use a database.
> 
> Lastly, this is not a result of Ruby, but a result of web applications in
> general since dealing with code running on the internet, servers, and
> clients is a whole lot different than dealing with code running on one
> computer.
> 
> Ruby passes objects by reference. So if you wrote a Ruby program, then you
> can pass around references etc.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/issues/7#issuecomment-6976855

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by mvillena3** [comment]
About our log system I saw code like this

``` Ruby
#app/controller/emails_controller.rb
wr_log_entry = WrLog.new(action:"email", sender_id:find_or_register(@email.from),
  receiver_id:find_or_register(@email.to), email_id:@email.id, responded: false)
```

Ideally, we would like to create has_many association within the Email's model and belongs_to in the WrLog model (http://guides.rubyonrails.org/association_basics.html) that allows for something like this instead

``` Ruby
# app/controller/emails_controller.rb
wr_log_entry = @email.wrlogs.new(action:"email", sender_id:find_or_register(@email.from),
                                 receiver_id:find_or_register(@email.to), responded: false)
```

Note, that I do not have to insert an email id since it is inferred from the `@email` object that is being acted upon.
Also, the find_or_register within the sender_id and receiver_id does not work since you cannot store objects in an integer id. 

If you are finding this task with model association and database management too complicated, then I can establish the associations.

**Comment by mvillena3** [comment]
I forgot to mention that the model associations allow for the creation of log_entries associated with an email as well as allow us to query all logs associated with an email.

**Comment by jhm15217** [comment]
Yes, show me what they should be. I understand that emails and wr_logs
should point at each other, but don't get the syntax yet. Also, how do you
know we shouldn't do it for wr_log's receiver_id and sender_id as well?

On Thu, Jul 19, 2012 at 1:52 PM, mvillena3 <
reply@reply.github.com

> wrote:
> 
> About our log system I saw code like this
> 
> ``` Ruby
> #app/controller/emails_controller.rb
> wr_log_entry = WrLog.new(action:"email",
> sender_id:find_or_register(@email.from),
>   receiver_id:find_or_register(@email.to), email_id:@email.id, responded:
> false)
> ```
> 
> Ideally, we would like to create has_many association within the Email's
> model and belongs_to in the WrLog model (
> http://guides.rubyonrails.org/association_basics.html) that allows for
> something like this instead
> 
> ``` Ruby
> # app/controller/emails_controller.rb
> wr_log_entry = @email.wrlogs.new(action:"email",
> sender_id:find_or_register(@email.from),
>                                  receiver_id:find_or_register(@email.to),
> responded: false)
> ```
> 
> Note, that I do not have to insert an email id since it is inferred from
> the `@email` object that is being acted upon.
> Also, the find_or_register within the sender_id and receiver_id does not
> work since you cannot store objects in an integer id.
> 
> If you are finding this task with model association and database
> management too complicated, then I can establish the associations.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jhm15217/worthreading/issues/7#issuecomment-7105685

## 

James H. Morris
http://www.cs.cmu.edu/~jhm
