### ISSUE TITLE
Should users list give email addresses?

### ISSUE THREAD

**Issue by jhm15217** [jhm15217/worthreading#71]
Privacy vs. convenience.  Maybe just do it for administrators.

**Comment by jhm15217** [comment]
If administrator goes to users profile page he/she can see his/her email.  BUT the digit "3" appears after each email. Weird!

**Comment by mvillena3** [comment]
Not sure why that is happening.

**Comment by jhm15217** [comment]
On heroku it seems to repeat a much of html from the page it is on.

**Comment by jhm15217** [comment]
You seem to have fixed the issue for the email address, but it still happens for the "Not Confirmed" comment which appears only on heroku.  I don't know how to do an ad hoc email through localhost.

**Comment by mvillena3** [comment]
Wait, so are you trying to toggle a user confirmed? You could use the console.

If you need to send an email locally using ours rails app, make sure you export the Mailgun SMTP settings to environment variables locally using export key=value. Then you can send an email using the rails console (UserMailer.method(args)) or local rails server.

**Comment by jhm15217** [comment]
Oh.

The other problem is how to receive an email locally. That requires
figuring out my ip address at the moment and having a mail server running.
That's beyond my competence.

On Fri, Aug 17, 2012 at 6:05 PM, mvillena3 notifications@github.com wrote:

> Wait, so are you trying to toggle a user confirmed? You could use the
> console.
> 
> If you need to send an email locally using ours rails app, make sure you
> export the Mailgun SMTP settings to environment variables locally using
> export key=value. Then you can send an email using the rails console
> (UserMailer.method(args)) or local rails server.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhm15217/worthreading/issues/71#issuecomment-7836470.

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
Now my local version won't work. It says undefined method `first_login_at'
for #User:0x007fed614b5040

On Fri, Aug 17, 2012 at 6:18 PM, james.morris@cmu.edu wrote:

> Oh.
> 
> The other problem is how to receive an email locally. That requires
> figuring out my ip address at the moment and having a mail server running.
> That's beyond my competence.
> 
> On Fri, Aug 17, 2012 at 6:05 PM, mvillena3 notifications@github.comwrote:
> 
> > Wait, so are you trying to toggle a user confirmed? You could use the
> > console.
> > 
> > If you need to send an email locally using ours rails app, make sure you
> > export the Mailgun SMTP settings to environment variables locally using
> > export key=value. Then you can send an email using the rails console
> > (UserMailer.method(args)) or local rails server.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/jhm15217/worthreading/issues/71#issuecomment-7836470.
> 
> ## 
> 
> James H. Morris
> http://www.cs.cmu.edu/~jhm

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
I had just done a git pull

On Fri, Aug 17, 2012 at 6:24 PM, james.morris@cmu.edu wrote:

> Now my local version won't work. It says undefined method
> `first_login_at' for #User:0x007fed614b5040
> 
> On Fri, Aug 17, 2012 at 6:18 PM, james.morris@cmu.edu wrote:
> 
> > Oh.
> > 
> > The other problem is how to receive an email locally. That requires
> > figuring out my ip address at the moment and having a mail server running.
> > That's beyond my competence.
> > 
> > On Fri, Aug 17, 2012 at 6:05 PM, mvillena3 notifications@github.comwrote:
> > 
> > > Wait, so are you trying to toggle a user confirmed? You could use the
> > > console.
> > > 
> > > If you need to send an email locally using ours rails app, make sure you
> > > export the Mailgun SMTP settings to environment variables locally using
> > > export key=value. Then you can send an email using the rails console
> > > (UserMailer.method(args)) or local rails server.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHubhttps://github.com/jhm15217/worthreading/issues/71#issuecomment-7836470.
> > 
> > ## 
> > 
> > James H. Morris
> > http://www.cs.cmu.edu/~jhm
> 
> ## 
> 
> James H. Morris
> http://www.cs.cmu.edu/~jhm

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
Never mind. I should have remembered to migrate.

On Fri, Aug 17, 2012 at 6:24 PM, james.morris@cmu.edu wrote:

> I had just done a git pull
> 
> On Fri, Aug 17, 2012 at 6:24 PM, james.morris@cmu.edu wrote:
> 
> > Now my local version won't work. It says undefined method
> > `first_login_at' for #User:0x007fed614b5040
> > 
> > On Fri, Aug 17, 2012 at 6:18 PM, james.morris@cmu.edu wrote:
> > 
> > > Oh.
> > > 
> > > The other problem is how to receive an email locally. That requires
> > > figuring out my ip address at the moment and having a mail server running.
> > > That's beyond my competence.
> > > 
> > > On Fri, Aug 17, 2012 at 6:05 PM, mvillena3 notifications@github.comwrote:
> > > 
> > > > Wait, so are you trying to toggle a user confirmed? You could use the
> > > > console.
> > > > 
> > > > If you need to send an email locally using ours rails app, make sure
> > > > you export the Mailgun SMTP settings to environment variables locally using
> > > > export key=value. Then you can send an email using the rails console
> > > > (UserMailer.method(args)) or local rails server.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHubhttps://github.com/jhm15217/worthreading/issues/71#issuecomment-7836470.
> > > 
> > > ## 
> > > 
> > > James H. Morris
> > > http://www.cs.cmu.edu/~jhm
> > 
> > ## 
> > 
> > James H. Morris
> > http://www.cs.cmu.edu/~jhm
> 
> ## 
> 
> James H. Morris
> http://www.cs.cmu.edu/~jhm

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
Finally, fixed. Use - instead of =!
