### ISSUE TITLE
The WR button doesn't show text when graphics are turned off

### ISSUE THREAD

**Issue by jhm15217** [jhm15217/worthreading#78]
Just a box

**Comment by jhm15217** [comment]
I just witnessed a user not turning on images.

**Comment by mvillena3** [comment]
The alternative should be a regular link with the text Worth Reading. That's odd

**Comment by mvillena3** [comment]
I'll see what I can figure out.

**Comment by mvillena3** [comment]
It seems to be isolated to the browser Chrome only. Trying to figure out a workaround.

**Comment by mvillena3** [comment]
Alright a fix is up. Test it out and ensure its working properly.

**Comment by mvillena3** [comment]
Closing since this was fixed.
