### ISSUE TITLE
Parse Email for More, Like buttons, etc.

### ISSUE THREAD

**Issue by mvillena3** [jhm15217/worthreading#9]
Need to be able to convert special notation in emails into more and like buttons

**Comment by jhm15217** [comment]
Even though the basic operation returns just one part, I guess a helper should do the parsing and return an array of all the parts, possibly cached someday.

**Comment by jhm15217** [comment]
I think we should add More buttons, soon. I'm thirsty for more feedback from our users, and this would force it. It's also worth understanding how people feel about WR button. If we see someone click through all the More buttons, but fail to click WR, that's intereting.

**Comment by mvillena3** [comment]
1) What columns would we need added to the WrLogs columns? Would we need a more column to record the times the more button is clicked as an array? 

2) I'm guessing the email_part column of the WrLog will be used to which part of the email they have seen? I suppose we should also record the maximum number of parts the email was split into as a column in either the email or wr_log. 

3) So let me get a check on the process of this. 
a) A user gets an email with the 1st part of the message. 
b) Then by clicking to more button they get the 2nd part of the message which is displayed on our site. 
c) At the bottom of the page on our site there can either be a worth reading button or another more button that leads to another page.

**Comment by jhm15217** [comment]
On Tue, Aug 21, 2012 at 4:51 PM, mvillena3 notifications@github.com wrote:

> 1) What columns would we need added to the WrLogs columns? Would we need a
> more column to record the times the more button is clicked as an array?
> 
> I don't think we really need to track the times a more button is clicked.
> The last_updated entry will be enough to tell us if the person did
> anything.
> 
>  2) I'm guessing the email_part column of the WrLog will be used to which
> part of the email they have seen?
> 
> Yes. Each more button should tell us what part the person is looking for,
> so it's even redundant except for keeping history.
> 
> I suppose we should also record the maximum number of parts the email was
> split into as a column in either the email or wr_log.
> 
> I would store it in the email entry. The simplest program would re-parse
> the message every time, so you might not even know it.
> 
>  3) So let me get a check on the process of this.
> a) A user gets an email with the 1st part of the message.
> 
> Yes
> 
> b) Then by clicking to more button they get the 2nd part of the message
> which is displayed on our site.
> 
> Yes
> 
> c) At the bottom of the page on our site there can either be a worth
> reading button or another more button that leads to another page.
> 
> Yes.
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/jhm15217/worthreading/issues/9#issuecomment-7915687.

## 

James H. Morris
http://www.cs.cmu.edu/~jhm

**Comment by jhm15217** [comment]
Clicking the See More link takes me to the original email message, not the continuation of the message after the <more>
